spring:
  application:
    name: ai-zero-code
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zerocode
    username: root
    password: `${MYSQL_PASSWORD:}
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: '/api'

# AI
langchain4j:
  open-ai:
    chat-model:
          base-url: https://api.deepseek.com
          api-key: <Your API Key>
          model-name: deepseek-v4-flash
          log-requests: true
          log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true



# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cyx.aizerocode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

