spring:
  application:
    name: ai-zero-code
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zerocode
    username: root
    password: `${MYSQL_PASSWORD:}
  #Redis
  data:
    redis:
      port: 6379
      password:
      ttl: 3600
      database: 0
      host: localhost
  # 后端 session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: '/api'
    # 前端 cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# AI
langchain4j:
  open-ai:
    chat-model:
          base-url: https://api.deepseek.com
          api-key: <Your API Key>
          model-name: deepseek-v4-flash
          log-requests: true
          log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-v4-flash
      log-requests: true
      log-responses: true



# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cyx.aizerocode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

